### 1. __init__.py

is used for packages

mydir/spam/__init__.py
mydir/spam/module.py
and mydir is on your path, you can import the code in module.py as

import spam.module
or

from spam import module
If you remove the __init__.py file, Python will no longer look for submodules inside that directory, so attempts to import the module will fail.

The __init__.py file is usually empty, but can be used to export selected portions of the package under more convenient name, hold convenience functions, etc. Given the example above, the contents of the init module can be accessed as

import spam

http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html

# 2  Functional programming Basics

functions are first class arguments 
they can take functions as arguments and return functions. ie functions can be used as data

## Lambdas:
these are anonymous functions. They do not have name associated with them.  
limited to one expression   

form :  lambda x,y,...: x+y+z..  

### Map
Map takes a function and a iterable- it evaluates the function on each iterable and returns the values.  

### Filter
filter takes a function and a iterable.   
it evaluates the function condition on each element and returns only the elements for which the function condition is true   

### Reduce
accumulates and returns a single result.  
eg: reduce(lambda x,y:x+y,[1,2,3]) "----> 6"  

#### differences:
map:takes any function that can be applied to individual elements  
filter:takes a conditional function  
reduce:takes an accumulator funnction  

# 3 Decorators
* A decorator is a function that takes a function as its only argument and returns a function
* A decorator replaces a function with a new decorated function

* http://blog.apcelent.com/python-decorator-tutorial-with-example.html
eg  below




In [2]:

def func(x):
    return x
func=func(func)

#or 
@func
def func(x):
    return x

* Functions themselves have attributes and dunder methods as functions are first class objects in python

* Example of inner function below

In [3]:
def add_by(x):
    def inner(y):
        return x+y
    return inner

add1=add_by(1)
add1(4) #5
add_by(5)(10) #15

##
def add_by(x):
    return lambda y:x+y


In [4]:
import json

def as_json(func):
    def inner(*args,**kwargs):
        result=func(*args,**kwargs)
        return json.dumps(result)
    return inner
#

@as_json
def func(x,y):
    return {"result":x+y}

print(func(3,4))

{"result": 7}


* the decorators however change the name of the function . To not do that from functools import wraps ,and decorate all of the inner functions with @wraps decorator

* to define a decorator which takes in arguments , just use an extra layer of function . Noe the decorator will have three layers of function instead of two layers .

### Closures

From this example you can see that closures - the fact that functions remember their enclosing scope - can be used to build custom functions that have, essentially, a hard coded argument. We aren’t passing the numbers 1 or 2 to our inner function but are building custom versions of our inner function that "remembers" what number it should print.

This alone is a powerful technique - you might even think of it as similar to object oriented techniques in some ways: outer is a constructor for inner with x acting like a private member variable. And the uses are numerous - if you are familiar with the key parameter in Python’s sorted function you have probably written a lambda function to sort a list of lists by the second item instead of the first. You might now be able to write an itemgetter function that accepts the index to retrieve and returns a function that could suitably be passed to the key parameter.

But let’s not do anything so mundane with closures! Instead let’s stretch one more time and write a decorator!

### Underscore

*  A single underscore before a variable is used to indicate a provate variable. that means when importing these functions or variables are not imported. But in python nothing is truly private
https://hackernoon.com/understanding-the-underscore-of-python-309d1a029edc

# 4 More Functional Programming

* A function which accepts a function as an argument or returns a function is called a higher order function.

* Iterators:
Anything for which next function is defined

## Generators
* Generator expressions can be created in a list comprehension way too
(x*x for x in [2,3,4])

* Use yield to create a generator in a function instead of return.
  you can still change variables after using yield
 
* cannot mix yield and return 
  
* They save ton loads of memory.

![title](relationships.png)

credit - http://nvie.com/posts/iterators-vs-generators/

## Iterators:
* You can pass an iterator into any container
* you can loop over them only once
* To make your object iterator ,implement __iter__ method in your class.


## Itertools

* itertools.tee allow you to construct duplicate iterators , so that you can loop over them multiple times.




# 5.Assorted

 * sys.getsizeof to find the memory of a variable in python
 * list.sort() sorts a list
 * looping through dictionary with items(iter.itervalues in py2.7)
 * To loop over two or more sequences at the same time, the entries can be paired with the zip() function
 * To loop over a sequence in sorted order, use the sorted() function which returns a new sorted list while leaving the source unaltered
 * To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the reversed() function.
 * The built-in function dir() is used to find out which names a module defines
 * The str() function is meant to return representations of values which are fairly human-readable, while repr() is meant to generate representations which can be read by the interpreter
 * dir() and ?function(),help function gives us information 
 
 * The single star * unpacks the sequence/collection into positional arguments. The double star ** does the same, only using a dictionary and thus named arguments:
 
 * id() gives the unique id of a reference


* repr() is intended to be unambiguous. str() is intended to be readable.

 
 ## Reading and writing
 
 * It is good practice to use the "with" keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point. Using with is also much shorter than writing equivalent try-finally blocks:
 
 * For reading lines from a file, you can loop over the file object. This is memory efficient, fast, and leads to simple code
 
 * If you want to read all the lines of a file in a list you can also use list(f) or f.readlines().
 
 ## Data Structures
 
 * string and list indexing  - a[start:stop:step] . To reverse a[::-1]

  ### Dictionaries:
   * d={}, d.get(color,0)
  ### Deque 

 
 

# 6. Classes

* class variable- common to all classes. They can keep track of information across all instances
* instance variables - each instance of the class has its own value
* Regular methods in a class automatically takes self as the first argument.
* class methods are created with class method decorator 
* class methods take class as first argument
* class methods can be used as alternative constructors
* static methods don't take any argument automatically
* static methods are similar to normal regular functions except that they may be appropriate to the class we are dealing with 
* static methods are created with static method decorator 

### Inheritence
* We can inherit from other classes .
* methods can be overridden. Init method can be overridden by using super().__init__

### Special/dunder methods
__inti__  
__repr__  
__str__  
__iter__  
are some examples of dunder methods

# 7.  Python Standard Library

## OS
* gives access to getcwd(),chdir(),makedirs(),listdir() etc 
* environ gives environment variables

## String formatting
* always use it.

# 8. Ipython

* %lsmagic gives Magic commands 
* %reset clears the namespace
* %hist gives the history
* %timeit 
* %logstart writes log to 
* output = !cmd args Run cmd and store the stdout in output
* %paste - pastes in a code format
* %whos- information about all the variables in the current session
* %alias alias_name cmd Define an alias for a system (shell) command
    %bookmark Utilize IPython’s directory bookmarking system  
    %cd directory Change system working directory to passed directory  
    %pwd Return the current system working directory  
    %pushd directory Place current directory on stack and change to target directory  
    %popd Change to directory popped off the top of the stack  
    %dirs Return a list containing the current directory stack  
    %dhist Print the history of visited directories  
    %env Return the system environment variables as a dict  
* Starting a line in IPython with an exclamation point !, or bang, tells IPython to execute
  everything after the bang in the system shell.     


## timing and profiling 

*  Profiling code is closely related to timing code, except it is concerned with determining
    where time is spent
* A common way to use cProfile is on the command line, running an entire program
  and outputting the aggregated time per function    
  
* . IPython has a convenient interface to this capability using the %prun command and the -p option
   to %run. %prun takes the same “command line options” as cProfile but will profile an
   arbitrary Python statement instead of a while .py file:  
  


# 9. Numpy

* numpy.random.rand(a1,a2,....): creates a random nd array of shape(a1,a2,..)
* we can query the shape with data.shape  . It is an attribute rather than a function    
* np.array function accepts a sequence to create an array 
* np.zeros,np.zeros_like,np.ones,np.ones_like,np.empty,np.empty_like are some functions to create arrays
* np.arange is used to create a sequence 
* you can cast a dtype by the function arr.astype()
* Calling astype always creates a new array (a copy of the data), even if
  the new dtype is the same as the old dtype.
  
  
### Operations between array and scalar

*  Any arithmetic operations between equal-size arrays applies the operation elementwise

### Basic Indexing and Slicing 
* like normal list slicing  a [start:stop:step]
*  An important first distinction from lists is that array slices are views on the original array. This means that
   the data is not copied, and any modifications to the view will be reflected in the source array
* If you want a copy of a slice of an ndarray instead of a view, you will
  need to explicitly copy the array; for example arr[5:8].copy().   
  
* In multidimensional case you can index by different forms

In [1]:
## multi dimensional array slicing
import numpy as np
a= np.array([[1,2,3],[2,3,4],[4,5,6],[7,8,9]])
print (a)
print(a[2,2])
print(a [2][2])
print( a[(1,2),(2,2)] )
print(a[1:,2:] )

[[1 2 3]
 [2 3 4]
 [4 5 6]
 [7 8 9]]
6
6
[4 6]
[[4]
 [6]
 [9]]


### Boolean indexing

* We can create a mask ,and pass that to the array to index

    mask=data<0  
    data[mask]=0


### Fancy Indexing

* Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays

* Suppose we had a 8 × 4 array:
     array([[ 0., 0., 0., 0.],
         [ 1., 1., 1., 1.],
         [ 2., 2., 2., 2.],
         [ 3., 3., 3., 3.],
         [ 4., 4., 4., 4.],
         [ 5., 5., 5., 5.],
         [ 6., 6., 6., 6.],
         [ 7., 7., 7., 7.]])  
     To select out a subset of the rows in a particular order, you can simply pass a list or
     ndarray of integers specifying the desired order:  
      arr[[4, 3, 0, 6]] ----->  
      array([[ 4., 4., 4., 4.],
             [ 3., 3., 3., 3.],
             [ 0., 0., 0., 0.],
             [ 6., 6., 6., 6.]])
     Passing multiple index arrays does something slightly different; it selects a 1D array of
     elements corresponding to each tuple of indices:   
      arr[[1, 5, 7, 2], [0, 3, 1, 2]] -------->array([1,5,7,2])  
      
      To get multiple rows and columns  
      arr[[1,5,7,2]][:,[0,3,1,2]] --------> array([[ 1.,  1.,  1.,  1.],
                                                   [ 5.,  5.,  5.,  5.],
                                                   [ 7.,  7.,  7.,  7.],
                                                   [ 2.,  2.,  2.,  2.]])
      Another way is to use the np.ix_ function, which converts two 1D integer arrays to an
      indexer that selects the square region:   
      arr[np._ix([1,5,7,2],[0,3,1,2])] --------> array([[ 1.,  1.,  1.,  1.],
                                                       [ 5.,  5.,  5.,  5.],
                                                       [ 7.,  7.,  7.,  7.],
                                                       [ 2.,  2.,  2.,  2.]])
      Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.                                                 


### Transpose,permutations and swapping axis

* simple transpose ---> arr.T
* swap axis 
   arr =np.array([[[ 0, 1, 2, 3],
         [ 8, 9, 10, 11]],
         [[ 4, 5, 6, 7],
         [12, 13, 14, 15]]])
   arr.swapaxes(1,2) ---->      array([[[ 0,  8],
                                        [ 1,  9],
                                        [ 2, 10],
                                        [ 3, 11]],

                                       [[ 4, 12],
                                        [ 5, 13],
                                        [ 6, 14],
                                        [ 7, 15]]])


         

### Universal Functions: Fast Element-wise Array Functions
* There are two types : unary ufuncs(abs,add,log,exp ,etc) and binary ufuncs(add,subtract,multiply,etc)
* they act element wise


### Expressing conditional logic as array operations

In [6]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])


result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
print(result)

result = np.where(cond, xarr, yarr)
print(result)

arr = np.random.randn(4, 4)
print(arr)
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2



[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]
[ 1.1  2.2  1.3  1.4  2.5]
[[ 0.90075418  0.16679508  0.45426646  0.18174287]
 [-0.11260066  0.06551077  1.19528923 -0.8552179 ]
 [-0.73740248 -0.70275337  1.27751912  0.55344916]
 [-0.615925   -0.63455435  1.9057229  -1.44692864]]


array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.11260066,  2.        ,  2.        , -0.8552179 ],
       [-0.73740248, -0.70275337,  2.        ,  2.        ],
       [-0.615925  , -0.63455435,  2.        , -1.44692864]])

### Mathematical and Statistical Methods

sum :Sum of all the elements in the array or along an axis. Zero-length arrays have sum 0.  
mean :Arithmetic mean. Zero-length arrays have NaN mean.  
std, var :Standard deviation and variance, respectively, with optional degrees of freedom adjustment  
(default denominator n).  
min, max:  Minimum and maximum.   
argmin, argmax :Indices of minimum and maximum elements, respectively.  
cumsum :Cumulative sum of elements starting from 0  
cumprod : Cumulative product of elements starting from 1  


####
0 axis refers to reduce over column, and 1 axis refers to reduce over row

### Methods for Boolean Arrays



In [7]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

47

In [8]:
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())

True
False


### Sorting 

Like Python’s built-in list type, NumPy arrays can be sorted in-place using the sort
method:

In [9]:
arr = np.random.randn(8)
print(arr)
arr.sort()
print(arr)

[-0.21706048  0.54325765 -0.39091516 -0.5849242   0.10696251 -1.23559697
 -0.88265301  0.0890195 ]
[-1.23559697 -0.88265301 -0.5849242  -0.39091516 -0.21706048  0.0890195
  0.10696251  0.54325765]


In [10]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.5984915363254169

* Multidimensional arrays can have each 1D section of values sorted in-place along an
  axis by passing the axis number to sort:

### Unique and Other Set Logic


In [11]:
## np.unique()
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [12]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [13]:
## in1d
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

### File Input and Output with Arrays

In [14]:
## save
arr = np.arange(10)
np.save('some_array', arr)

In [15]:
## load
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
##You save multiple arrays in a zip archive using np.savez and passing the arrays as keyword
##arguments:

np.savez('array_archive.npz', a=arr, b=arr)
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Linear algebra


In [17]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [18]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

array([[-3.84532452,  1.35773073, -0.08981066, -5.57736965, -2.52140486],
       [ 0.        , -6.17009771, -3.54017388, -1.29300315,  2.47074836],
       [ 0.        ,  0.        , -8.26782207,  1.70930942,  3.33485107],
       [ 0.        ,  0.        ,  0.        , -1.56142987, -0.08197386],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.08682534]])

### Random number generation


seed :Seed the random number generator  
permutation: Return a random permutation of a sequence, or return a permuted range   
shuffle :Randomly permute a sequence in place  
rand: Draw samples from a uniform distribution  
randint: Draw random integers from a given low-to-high range  
randn: Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)  
binomial: Draw samples a binomial distribution  
normal: Draw samples from a normal (Gaussian) distribution  
beta :Draw samples from a beta distribution  
chisquare: Draw samples from a chi-square distribution  
gamma: Draw samples from a gamma distribution  
uniform: Draw samples from a uniform [0, 1) distribution  

### Stacking

* stack : Join a sequence of arrays along a new axis. The `axis` parameter specifies the index of the new axis in the dimensions of the result. For example, if ``axis=0`` it will be the first dimensionand if ``axis=-1`` it will be the last dimension.

* vstack : Stack arrays in sequence vertically (row wise).
* hstack : Stack arrays in sequence horizontally (column wise).
* dstack : Stack arrays in sequence depth wise (along third dimension).
* concatenate : Join a sequence of arrays along an existing axis.
* vsplit : Split array into a list of multiple sub-arrays vertically.




In [19]:
a=np.ones([2,3,4])
b=np.zeros([2,3,4])
c=np.stack((a,b))
print(a.shape)
print(b.shape,"\n")

print(c.shape,"\n")


a=a.reshape([1,*a.shape])
b=b.reshape([1,*b.shape])


print(a.shape)
print(b.shape,"\n")

c=np.vstack((a,b))

print(c.shape)


(2, 3, 4)
(2, 3, 4) 

(2, 2, 3, 4) 

(1, 2, 3, 4)
(1, 2, 3, 4) 

(2, 2, 3, 4)


## Image Manipulation


